### ISSUE TITLE
3dtiles模型加载模型散架

### ISSUE THREAD

**Issue by wang88633** [maptalks/issues#166] opened 2022-10-31 07:02 UTC

**Comment by wang88633** [comment] 2022-10-31 07:08
![image](https://user-images.githubusercontent.com/22592035/198951055-5d0f87de-5a9e-4128-bcb7-f5596e8d9427.png)

**Comment by fuzhenn** [comment] 2022-10-31 07:35
duplicate of #164

**Closed as completed by fuzhenn** 2022-10-31 07:35 UTC
